# Fly.io Configuration for 喂喂機 (WeiWei Voice Agent)

app = "weiweiji"
primary_region = "hkg"  # Hong Kong region for lowest latency

[build]

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Allow WebSocket connections
[mounts]

