# fly.toml app configuration file generated for cantonese-agent on 2025-10-22T18:44:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cantonese-agent'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
